## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://discutivo.com:3306/discu351_proyectodaw?useSSL=false
userDB: discu351_daw
passDB: nohay2sin3
mailFrom: dawcrud@gmail.com
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: nohay2sin3
##1hora
timeToValidate: 1
